### ISSUE TITLE
[Feat] 메인 페이지 작업

### ISSUE THREAD

**Issue by soheedev** [today-zipsa/TodayZipsa#107]
- [x] homePage.js, home.js, home.css 파일을 신규 등록한다.
- [x] 메인에 render하기 위해 router.js 를 수정한다.
- [x] main을 제외한 나머지는 공통헤더와 풋터를 가져온다.
- [x] main에는 카테고리별로 4개상품을 노출시키며 더보기 버튼이 추가된다. (총 4개 라인)
- [x] 메인베너는 swiper로 메인 이미지 4개가 로테이션된다.(희서님도움)

**Comment by gygy7151** [comment]
#169
