### ISSUE TITLE
[Doc] 어드민 계정 및 임시 회원 계정 생성 및 공유

### ISSUE THREAD

**Issue by gygy7151** [today-zipsa/TodayZipsa#108]
# Summary
- 어드민 계정은 팀원들하고만 공유
- 추후 서비스 배포후 서비스를 사용해보고 싶은 일반인들을 대상으로 임시 회원 계정을 생성할 필요가 있음.

# 필수요구사항
 - [x] 어드민 계정을 생성하여 id와 pw를 노션에 공유한다.
 - [x] 임시 회원 계정을 생성하여 id와 pw를 노션에 공유한다.

**Comment by ronieo** [comment]
이슈 확인했습니다! 로직 적용 하고 검증 후에 이슈 내용 공유 드리도록 하겠습니다 :)

**Comment by soheedev** [comment]
계정 생성했습니다.
비번이 넘 짧으면 생성이 안되서 8자리로 만들었습니다.

일반유저: zipsa@user.com / 1234qwer
어드민   : admin@zipsa.com / 1q2w3e4r

**Comment by ronieo** [comment]
이슈 닫겠습니다 :))
