### ISSUE TITLE
[Feat] 회원가입 및 로그인 후 로컬스토리지에 저장되어야 할 데이터 목록 추가 작업 및 어드민 id 등록 예외처리

### ISSUE THREAD

**Issue by gygy7151** [today-zipsa/TodayZipsa#109]
# 필수 요구사항
- [x] 회원가입 및 로그인 후   accessToken,email,displayName,profileImg 로컬스토리지에 저장한다.
- [x] 'admin@zipsa.com' id명으로 회원가입 시도시 '올바르지 않은 id값입니다'라는 안내문구를 노출시킨다.
- [x] 'admin@zipsa.com' id명 입력후 회원가입 버튼을 눌렀을때, '올바르지 않은 id값입니다'라는 모달창을 띄운다.

**Comment by ronieo** [comment]
이슈 확인 했습니다!
