### ISSUE TITLE
[Feat] 공통헤더 '반가워요, 집사님!' 버튼 마이페이지 및 어드민 페이지 라우팅 로직 추가

### ISSUE THREAD

**Issue by gygy7151** [today-zipsa/TodayZipsa#111]
# 필수 요구사항
- [x] '어드민 계정'으로 로그인한 경우, 공통헤더 '반가워요, 집사님!' 버튼 클릭시  '/admin'으로 이동
- [x] 그외 타 계정으로 로그인한 경우, 공통헤더 '반가워요, 집사님!' 버튼 클릭시  '/my'로 이동

**Comment by ronieo** [comment]
이슈확인했습니다!

**Comment by gygy7151** [comment]
#115
