### ISSUE TITLE
[Fix] 이미지 클릭 시 상세페이지 연결 문제

### ISSUE THREAD

**Issue by hlee686** [today-zipsa/TodayZipsa#137]
`const aTag = document.createElement("a")
            aTag.href = "/detail"
            imgEl.addEventListener("click", function(){
                location.replace(aTag.href +"?id=" + json[i].id)
            })
`

이미지 클릭 시 상세페이지로 연결 되는 부분입니다. 제 로컬에서 작동이 제대로 안되는데, "만약 다른 분들도 연결이 안된다면", 새로운 로직이 필요할 것 같습니다.

**Comment by gygy7151** [comment]
@soheedev 소희님~ 이부분 확인 부탁드립니당!

**Comment by soheedev** [comment]
detailPage.js 샘플입니다.
----
import { request } from "../../api/common";

export default function detailPage(strProductId) {
  console.log("strProductId>>> ", strProductId);

  const datailPage = document.createElement("div");
  const detailImgEl = document.createElement("img");

  getProductDetail(strProductId);

  //api 호출
  async function getProductDetail(productId) {
    const res = await request("PRD07", { productId });
    console.log(res);
    detailImgEl.src = res.photo;
  }

  datailPage.append(detailImgEl);
  return datailPage;
}

**Comment by soheedev** [comment]
router.js 부분에는 상품ID를 받아서 처리할 부분이 필요합니다.
--------
"/detail/:productId": (match) => {
      const { productId } = match?.data;
      console.log({ productId });
      renderPage([Header, detailPage(productId), Footer]); // detailPage페이지에 상품id값을 넘겨서 화면을 그립니다.
    },

**Comment by gygy7151** [comment]
#169
