### ISSUE TITLE
[Feat] 어드민 페이지 필수요구사항

### ISSUE THREAD

**Issue by ronieo** [today-zipsa/TodayZipsa#24]
- [x]  상품 구매 ‘확정’ 버튼이 있어야 한다.
- [x]  상품 구매 ‘취소’ 버튼이 있어야 한다.
- [x] 상품 거래 ID값이 보여야 한다.
- [x] 상품 거래 id를 클릭하면 상품 상세 페이지로 이동해야 한다. ex. /detail/{id}
    - [x] 상품 거래 id를 클릭하면 상품 상세 페이지로 이동해야 한다.
- [x]  상품 ‘삭제’ 버튼이 있어야 한다. → 보통은 3년~5년 보유하는 경우가 많아서 삭제가 안되는 경우가 많음.
    - [x]  삭제시 판매 이력전체 리스트에서 해당제품 id를 검색후, id존재시 삭제불가 제품안내 문구를 띄운다.
- [x]  상품 ‘수정’ 버튼이 있어야 한다. (상품태그,상품항목사진, 상품명, 상품설명,상품가격, SoldOut 모두 수정가능)

**Comment by gygy7151** [comment]
#169
