### ISSUE TITLE
[Fix] 공통 API 관련 

### ISSUE THREAD

**Issue by soheedev** [today-zipsa/TodayZipsa#36]
# 필수요구사항
- [x] API Request 요청을 common.js 파일로 모듈화한다.

**Comment by gygy7151** [comment]
제목 컨벤션 맞춰서 작성 부탁드립니다~
[common] -> [Feat] (o)
공통기능이 무엇과 관련된 공통기능인지 제목에 명시하여 수정 부탁드립니다~
@soheedev
