### ISSUE TITLE
[Fix] 자동차 한글검색도 가능하게 기능 추가하기

### ISSUE THREAD

**Issue by hlee686** [today-zipsa/TodayZipsa#42]
- [ ] <del> i.e. "Lexus" 또는 "렉서스" 둘다 검색 가능하도록 modify하기 <del>

**Comment by gygy7151** [comment]
@hlee686 이슈 제목 컨벤션 맞춰주시길 부탁드립니다~ 희서님 우선은 제가 대신 컨벤션 맞게 제목 수정하였습니다!
<img width="188" alt="image" src="https://user-images.githubusercontent.com/55748886/219427295-188375d6-284a-47c1-a739-115103f9d4ab.png">
