### ISSUE TITLE
[Feat] 결제 페이지 필수 요구사항 기능 구현

### ISSUE THREAD

**Issue by hlee686** [today-zipsa/TodayZipsa#8]
# 결제페이지 필수요구사항
- [x]  상품정보가 보여야 한다. #99 
- [x]  등록된 계좌수단 정보가 보여야 한다.
- [x]  등록된 계좌의 잔액 정보가 보여야 한다.
- [x]  만약 계좌 잔액이 부족한 경우, ‘잔액이 부족합니다’라는 단순 텍스트 알림만 보여 주어야 한다.
- [x]  결제하기 버튼이 있어야 한다.
- [x]  결제하기 버튼을 눌렀을 때 결제불가 안내 모달창이 보여야 한다. 
    - [x] 잔액이 부족한 경우 '잔액이 부족합니다. 계좌를 추가해주세요.' 안내 모달창이 보여진 후, 마이페이지로 이동한다.
    - [x] 계좌가 없을 경우 '계좌를 추가해주세요.' 안내 모달창이 보여진 후, 마이페이지로 이동한다.

# 결제 완료페이지 필수요구사항
- [x]  계속 쇼핑하기 버튼이 있어야 한다.
- [x]  결재내역보기 버튼이 있어야 한다.
- [x]  ‘결제가 완료되었습니다’라는 문구가 있어야 한다.

# css작업
- [x] paymentPage.js
- [x] paymentDonepage.js

**Comment by gygy7151** [comment]
#169
